import type { Metadata } from "next";
import { Inter, Lexend } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] }); // Loading the Inter font with Latin subset
const lexend = Lexend({  weight: ['300', '400', '700'], subsets: ['latin'] }) // Loading the Lexend font with specified weights and Latin subset

// Metadata for the page
export const metadata: Metadata = {
  title: "Muzzix pannel",
  description: "Generated by create next app",
};

// Root layout component
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Rendering the HTML document with the specified language and body class
  return (
    <html lang="en">
      <body className={lexend.className}>{children}</body>
    </html>
  );
}
